# models/usage.py
"""Usage logging: the Usage dataclass and the Request model."""

import dataclasses
from typing import Any, ClassVar

from django.db import models
from django.utils import timezone

from .accounts import Token


@dataclasses.dataclass
class Usage:
    input_tokens: int = 0
    output_tokens: int = 0

    @property
    def total_tokens(self) -> int:
        return self.input_tokens + self.output_tokens

    def __add__(self, other: "Usage") -> "Usage | Any":
        if not isinstance(other, Usage):
            return NotImplemented
        return Usage(
            input_tokens=self.input_tokens + other.input_tokens,
            output_tokens=self.output_tokens + other.output_tokens,
        )

    def __sub__(self, other: "Usage") -> "Usage | Any":
        if not isinstance(other, Usage):
            return NotImplemented
        return Usage(
            input_tokens=self.input_tokens - other.input_tokens,
            output_tokens=self.output_tokens - other.output_tokens,
        )


class Request(models.Model):
    """Represents a request made using a custom Token."""

    input_tokens = models.PositiveIntegerField(
        default=0, help_text="Tokens consumed by the input for this request"
    )
    output_tokens = models.PositiveIntegerField(
        default=0, help_text="Tokens generated by the output for this request"
    )
    token = models.ForeignKey(
        Token,
        on_delete=models.CASCADE,  # If Token is deleted, delete its associated Requests
        related_name="requests",
    )
    model = models.CharField(
        max_length=255, blank=True, default="", help_text="Model used in request"
    )
    timestamp = models.DateTimeField(default=timezone.now, db_index=True)

    # Additional fields (endpoint_url removed)
    method = models.CharField(
        max_length=16, blank=True, help_text="HTTP method used (e.g., GET, POST, etc.)"
    )
    status_code = models.PositiveIntegerField(
        null=True, blank=True, help_text="HTTP status code returned by the endpoint"
    )
    response_time_ms = models.PositiveIntegerField(
        null=True, blank=True, help_text="Time taken by the API to respond, in milliseconds"
    )
    processing_time_ms = models.PositiveIntegerField(
        null=True,
        blank=True,
        help_text="Aqueduct overhead, or the processing time of the request before it is passed "
        "to the API, in milliseconds",
    )
    user_agent = models.CharField(
        max_length=256, blank=True, help_text="User agent string of the client making the request"
    )
    ip_address = models.GenericIPAddressField(
        null=True, blank=True, help_text="IP address from which the request originated"
    )
    path = models.CharField(
        max_length=512,
        blank=True,
        help_text="The specific API path requested after the base endpoint URL "
        "(e.g., '/chat/completions')",
    )
    user_id = models.CharField(
        max_length=256,
        blank=True,
        db_index=True,
        help_text="A string (user ID, email address, username, etc.) identifying "
        "the particular user who made the request, "
        "and who may be a different user than the token owner.",
    )

    class Meta:
        # Crucial for the rate limit query!
        indexes: ClassVar[list[models.Index]] = [
            models.Index(fields=["token", "timestamp"]),
            models.Index(fields=["model", "timestamp"]),
        ]
        ordering: ClassVar[list[str]] = ["-timestamp"]  # Optional: default ordering

    def __str__(self) -> str:
        return f"{self.id}"

    @property
    def token_usage(self) -> Usage:
        """Get a TokenUsage dataclass instance representing this request's token usage."""
        return Usage(input_tokens=self.input_tokens, output_tokens=self.output_tokens)

    @token_usage.setter
    def token_usage(self, usage: Usage) -> None:
        """Set input_tokens and output_tokens from a Usage dataclass instance."""
        if not isinstance(usage, Usage):
            raise TypeError("token_usage must be a Usage dataclass instance")
        self.input_tokens = usage.input_tokens
        self.output_tokens = usage.output_tokens
