services:
  database:
    container_name: postgres
    image: postgres:17.4-bookworm
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=directus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  directus:
    container_name: directus
    image: directus/directus:11.6.0
    ports:
      - 8055:8055
    depends_on:
      database:
        condition: service_healthy
    environment:
      SECRET: "replace-with-secure-random-value"

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      CACHE_ENABLED: "false"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "1234"

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: "https://directus.example.com"
    
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8055/server/ping | grep -q 'pong'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 10s
      start_period: 10s

    # Environment variables can also be defined in a file (for example `.env`):
    # env_file:
    #	  - .env
  
  migrate:
    container_name: directus-migrate
    image: directus-migrate
    build:
      context: ./migrate
    depends_on:
      directus:
        condition: service_healthy
    environment:
      URL: "http://directus:8055"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "1234"