services:
  migrate:
    build: .
    container_name: django_migrate
    command: python manage.py migrate
    volumes:
      - .:/app
    env_file:
      - .example.env
    depends_on:
      - db

  web:
    build: .
    container_name: django_app
    command: daphne -b 0.0.0.0 -p 8000 aqueduct.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .example.env
    depends_on:
      - migrate

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:
