# https://docs.docker.com/guides/dex/
include:
  - docker-compose.yaml

services:
  dex:
    image: dexidp/dex:v2.42.1
    container_name: dex
    ports:
      - "5556:5556"
    volumes:
      - ./mock-dex-config.yaml:/etc/dex/config.yaml
    command: [ "dex", "serve", "/etc/dex/config.yaml" ]