services:
  dex:
    image: dexidp/dex:v2.42.1
    container_name: dex
    ports:
      - "5556:5556"
    volumes:
      - ./mock-dex-config.yaml:/etc/dex/config.yaml
    command: [ "dex", "serve", "/etc/dex/config.yaml" ]

  migrate:
    build: .
    container_name: django_migrate
    command: python manage.py migrate
    env_file:
      - .example.env
    depends_on:
      - db

  web:
    build: .
    container_name: django_app
    command: |
      sh -c "python manage.py collectstatic --no-input && daphne -b 0.0.0.0 -p 8000 aqueduct.asgi:application"
    volumes:
      - ./example_router_config.yaml:/app/example_router_config.yaml
      - ./test-mcp.json:/app/test-mcp.json
    ports:
      - "8000:8000"
    env_file:
      - .example.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully
      dex:
        condition: service_started
    healthcheck:
      test: ["CMD", "python", "-c", "import sys, httpx; httpx.get('http://localhost:8000/health', timeout=4).raise_for_status()"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 2s

  redis:
    image: redis:8.2.1

  celery:
    build: .
    volumes:
      - ./example_router_config.yaml:/app/example_router_config.yaml
      - ./test-mcp.json:/app/test-mcp.json
    env_file:
      - .example.env
    depends_on:
      - redis
    command: celery -A aqueduct worker -l INFO

  celery-beat:
    build: .
    env_file:
      - .example.env
    depends_on:
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    command: celery -A aqueduct beat -l INFO

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .example.env

  tika:
    image: apache/tika:3.2.3.0
    ports:
      - "9998:9998"

  mcp-everything:
    image: node:20-slim
    container_name: mcp_everything
    command: npx @modelcontextprotocol/server-everything streamableHttp
    environment:
      - PORT=3001
    ports:
      - "3001:3001"

volumes:
  postgres_data:
