[project]
name = "aqueduct"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2",
    "mozilla-django-oidc>=4.0.1",
    "requests>=2.32.3",
]
