[project]
name = "aqueduct"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asgiref>=3.8.1",
    "daphne>=4.1.2",
    "django>=5.2",
    "httpx>=0.28.1",
    "mozilla-django-oidc>=4.0.1",
    "openai>=1.76.0",
    "whitenoise>=6.9.0",
]

[project.optional-dependencies]
postgresql = [
    "psycopg2-binary>=2.9.10",
]
vllm = [
    "vllm>=0.8.4",
]