[project]
name = "aqueduct"
version = "0.1.6"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asgiref>=3.8.1",
    "celery[redis]>=5.5.2",
    "daphne>=4.1.2",
    "django>=5.2",
    "django-celery-beat>=2.8.1",
    "django-silk>=5.4.0",
    "django-tos>=1.1.0",
    "httpx>=0.28.1, <1",
    "litellm==1.72.0",
    "mozilla-django-oidc>=4.0.1",
    "openai>=1.95.0",
    "whitenoise>=6.9.0",
]

[project.optional-dependencies]
postgresql = [
    "psycopg2-binary>=2.9.10",
]
vllm = [
    "vllm==0.8.4",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "tbump>=6.11.0",
]
