[project]
name = "aqueduct"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asgiref>=3.8.1",
    "django>=5.2",
    "httpx>=0.28.1",
    "mozilla-django-oidc>=4.0.1",
    "openai>=1.76.0",
]

[dependency-groups]
dev = [
    "daphne>=4.1.2",
]
