global:
  security:
    allowInsecureImages: true # allow legacy containers until a new solution is found
  postgresql:
    fullnameOverride: "postgresql"
    auth:
      username: aqueduct
      password: aqueduct
      database: aqueduct
      # existingSecret: ""
      # secretKeys:
      #   adminPasswordKey: ""
      #   userPasswordKey: ""
      #   replicationPasswordKey: ""
    service:
      ports:
        postgresql: "5432"

image:
  repository: ghcr.io/tu-wien-datalab/aqueduct
  tag: latest
  pullPolicy: IfNotPresent

djangoSecretKey:
    value: ""
    valueFrom:
      secretKeyRef:
        name: ""
        key: ""

oidc:
  signAlgo: "RS256"
  jwksEndpoint: ""
  authorizationEndpoint: ""
  tokenEndpoint: ""
  userEndpoint: ""
  clientId: "" # If using direct value
  clientSecret: "" # If using direct value
  # existingSecret: "" # Uncomment to use a secret
  # secretKeys:
  #   clientIdKey: ""
  #   clientSecretKey: ""


celery:
  brokerUrl: "redis://redis-master:6379/0"
  workerConcurrency: 1
  requestRetentionDays: 7
  schedule: "0 4 * * *"
  workerDeployment:
    replicas: 1
    resources: {}

silk:
  enabled: true

env:
  - name: DATABASE_ENGINE
    value: "django.db.backends.postgresql"
  # - name: DATABASE_ENGINE
  #   value: "django.db.backends.sqlite3"

settingsPy:
  extra: |
    # You can add/override settings here
    # OIDC_DEFAULT_GROUPS = ["default"]
    # ORG_NAME_FROM_OIDC_GROUPS_FUNCTION = lambda x: "default"
    # ADMIN_GROUP = "default"

# Router configuration for litellm router
routerConfig: {}

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations: { }
  host: chart-example.local
  path: /
  pathType: Prefix
  tls: false
  tlsSecretName: ""

postgresql:
  enabled: true
  image:
    repository: bitnamilegacy/postgresql
  primary:
    persistence:
      enabled: true
      size: 100Gi
    resources:
      limits:
        cpu: "8"
        memory: "24Gi"
      requests:
        cpu: "8"
        memory: "24Gi"

redis:
  fullnameOverride: "redis"
  architecture: standalone
  image:
    repository: bitnamilegacy/redis
  auth:
    enabled: false
  master:
    persistence:
      enabled: false

# PVC for files API root
persistence:
  files:
    enabled: true
    mountPath: /var/lib/aqueduct/files
    size: 10Gi
    storageClass: null
