"""
Django settings for management project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "insecure-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mozilla_django_oidc',
    'management.apps.AqueductManagementConfig',
    "gateway.apps.GatewayConfig"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mozilla_django_oidc.middleware.SessionRefresh',
]

AUTHENTICATION_BACKENDS = (
    # Add the Token backend - tries this first for API requests
    'gateway.authentication.TokenAuthenticationBackend',

    # Keep the custom OIDC backend for web login
    'management.auth.OIDCBackend',

    # Keep the default ModelBackend for Django admin login, etc.
    'django.contrib.auth.backends.ModelBackend',
)

# OIDC Settings

OIDC_RP_SCOPES = "openid email profile"
OIDC_RP_SIGN_ALGO = os.environ.get('OIDC_RP_SIGN_ALGO', 'RS256')
OIDC_OP_JWKS_ENDPOINT = os.environ.get('OIDC_OP_JWKS_ENDPOINT')

OIDC_RP_CLIENT_ID = os.environ.get('OIDC_RP_CLIENT_ID')
OIDC_RP_CLIENT_SECRET = os.environ.get('OIDC_RP_CLIENT_SECRET')

OIDC_OP_AUTHORIZATION_ENDPOINT = os.environ.get('OIDC_OP_AUTHORIZATION_ENDPOINT')
OIDC_OP_TOKEN_ENDPOINT = os.environ.get('OIDC_OP_TOKEN_ENDPOINT')
OIDC_OP_USER_ENDPOINT = os.environ.get('OIDC_OP_USER_ENDPOINT')

LOGIN_REDIRECT_URL = '/'  # Where to redirect after successful login
LOGOUT_REDIRECT_URL = '/login/'  # Where to redirect after successful logout
LOGIN_URL = '/login/'  # Where to redirect if user is not logged in

# Aqueduct Settings ------------------------------------------------------

MAX_USER_TOKENS = 3
MAX_SERVICE_ACCOUNTS_PER_TEAM = 10

OIDC_PROVIDER = 'SSO'


def my_org_name_extractor(groups: list[str]) -> str | None:
    # Your custom logic to extract the organization name from groups
    # Example:
    for group in filter(lambda g: g.startswith("E"), groups):
        return group.split("-")[0]
    return None


ORG_NAME_FROM_OIDC_GROUPS_FUNCTION = my_org_name_extractor
ADMIN_GROUP = "ds-ray-cluster"  # the admin group name

EXTRA_NAV_LINKS = {
    'GitHub': 'https://github.com/TU-Wien-dataLAB/aqueduct',  # Example external link
    'Bug Report': 'https://github.com/TU-Wien-dataLAB/aqueduct/issues/new?template=bug_report.md',
    # 'API Status': '/status/',  # Example internal path
    # 'About Us': 'about_page',  # Example named URL (assuming you have url(..., name='about_page'))
}

# ------------------------------------------------------------------------

ROOT_URLCONF = 'aqueduct.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Aqueduct processors
                'management.context_processors.settings'
            ],
        },
    },
]

# WSGI_APPLICATION = 'aqueduct.wsgi.application'
ASGI_APPLICATION = "aqueduct.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 1. First, get which database engine you want
DATABASE_ENGINE = os.getenv('DATABASE_ENGINE', 'django.db.backends.sqlite3')

# 2. Set up DATABASES based on the engine
DATABASES = {
    'default': {
        'ENGINE': DATABASE_ENGINE,
    }
}

# 3. If it's SQLite, fill in the NAME for the file
if DATABASE_ENGINE == 'django.db.backends.sqlite3':
    DATABASES['default']['NAME'] = str(BASE_DIR / 'db.sqlite3')
elif DATABASE_ENGINE == 'django.db.backends.postgresql':
    DATABASES['default'].update({
        'NAME': os.getenv('POSTGRES_DB', 'aqueduct'),
        'USER': os.getenv('POSTGRES_USER', 'aqueduct'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'aqueduct'),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    })
else:
    raise ImproperlyConfigured(f"Unsupported database engine: {DATABASE_ENGINE}")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STORAGES = {
    # ...
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
