# Generated by Django 5.2 on 2025-04-09 11:02

from django.db import migrations


def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name='user'),
        Group(name='org-admin'),
        Group(name='admin'),
    ])


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            'user',
            'org-admin',
            'admin'
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
