# Generated by Django 5.2 on 2025-06-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_initial_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='excluded_models',
            field=models.JSONField(default=list, help_text='Models to exclude from the config.'),
        ),
        migrations.AddField(
            model_name='team',
            name='excluded_models',
            field=models.JSONField(default=list, help_text='Models to exclude from the config.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='excluded_models',
            field=models.JSONField(default=list, help_text='Models to exclude from the config.'),
        ),
    ]
