# Generated by Django 5.2 on 2025-07-09 12:14

import django.db.models.deletion
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_model_exclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.CharField(default=management.models.generate_file_id, editable=False, help_text='The file identifier, which can be referenced in the API endpoints.', max_length=100, primary_key=True, serialize=False)),
                ('bytes', models.BigIntegerField(help_text='The size of the file, in bytes.')),
                ('created_at', models.PositiveIntegerField(help_text='The Unix timestamp (in seconds) for when the file was created.')),
                ('filename', models.CharField(help_text='The name of the file.', max_length=255)),
                ('purpose', models.CharField(choices=[('assistants', 'assistants'), ('batch', 'batch'), ('fine-tune', 'fine-tune'), ('vision', 'vision'), ('user_data', 'user_data'), ('evals', 'evals')], help_text='The intended purpose of the file.', max_length=20)),
                ('expires_at', models.PositiveIntegerField(blank=True, help_text='The Unix timestamp (in seconds) for when the file will expire.', null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='management.token')),
            ],
            options={
                'verbose_name': 'File Object',
                'verbose_name_plural': 'File Objects',
            },
        ),
    ]
