# Generated by Django 5.2 on 2025-08-27 08:03

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_files_batches_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='id',
            field=models.CharField(default=management.models.generate_batch_id, editable=False, help_text='The batch identifier.', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='batch',
            name='request_counts',
            field=models.JSONField(blank=True, default=management.models.default_request_counts, help_text='The request counts for different statuses within the batch.', null=True),
        ),
        migrations.AlterField(
            model_name='fileobject',
            name='purpose',
            field=models.CharField(choices=[('assistants', 'assistants'), ('assistants_output', 'assistants_output'), ('batch', 'batch'), ('batch_output', 'batch_output'), ('fine-tune', 'fine-tune'), ('vision', 'vision'), ('user_data', 'user_data'), ('evals', 'evals')], help_text='The intended purpose of the file.', max_length=20),
        ),
    ]
