# Generated by Django 5.2 on 2025-10-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_file_purpose_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="user_id",
            field=models.CharField(
                blank=True,
                help_text="A string (user ID, email address, username, etc.) identifying the particular user who made the request, and who may be a different user than the token owner.",
                max_length=256,
            ),
        ),
    ]
