# Generated by Django 5.2.7 on 2025-10-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_file_purpose_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='excluded_mcp_servers',
            field=models.JSONField(default=list, help_text='MCP servers to exclude from the config.'),
        ),
        migrations.AddField(
            model_name='org',
            name='merge_mcp_server_exclusion_lists',
            field=models.BooleanField(default=True, help_text="When enabled, this object's MCP server exclusion list will be combined with the exclusion list from its parent in the hierarchy (such as combining a User's and an Org's lists). Disable to use only this object's exclusions."),
        ),
        migrations.AddField(
            model_name='team',
            name='excluded_mcp_servers',
            field=models.JSONField(default=list, help_text='MCP servers to exclude from the config.'),
        ),
        migrations.AddField(
            model_name='team',
            name='merge_mcp_server_exclusion_lists',
            field=models.BooleanField(default=True, help_text="When enabled, this object's MCP server exclusion list will be combined with the exclusion list from its parent in the hierarchy (such as combining a User's and an Org's lists). Disable to use only this object's exclusions."),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='excluded_mcp_servers',
            field=models.JSONField(default=list, help_text='MCP servers to exclude from the config.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='merge_mcp_server_exclusion_lists',
            field=models.BooleanField(default=True, help_text="When enabled, this object's MCP server exclusion list will be combined with the exclusion list from its parent in the hierarchy (such as combining a User's and an Org's lists). Disable to use only this object's exclusions."),
        ),
    ]
