# Generated by Django 5.2.7 on 2025-11-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_mcp_server_exclusion"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="user_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="A string (user ID, email address, username, etc.) identifying the particular user who made the request, and who may be a different user than the token owner.",
                max_length=256,
            ),
        ),
    ]
