# Generated by Django 5.2.7 on 2026-02-18 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_request_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='errors',
        ),
        migrations.AddField(
            model_name='batch',
            name='token',
            field=models.ForeignKey(blank=True, help_text='The token (API key) that created this batch.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='management.token'),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='preview',
            field=models.TextField(blank=True, help_text='Preview of file content (first 10 lines for JSONL files)', null=True),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='upstream_url',
            field=models.URLField(blank=True, help_text='The upstream API URL this file was uploaded to', null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='error_file',
            field=models.ForeignKey(blank=True, help_text='The error file for the batch (set when batch completes with errors).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_batches', to='management.fileobject'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='output_file',
            field=models.ForeignKey(blank=True, help_text='The output file for the batch (set when batch completes).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_batches', to='management.fileobject'),
        ),
        migrations.CreateModel(
            name='VectorStore',
            fields=[
                ('id', models.CharField(editable=False, help_text='The vector store identifier.', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the vector store.', max_length=255)),
                ('expires_after', models.JSONField(blank=True, help_text='Expiration policy for the vector store.', null=True)),
                ('chunking_strategy', models.JSONField(blank=True, help_text='Chunking configuration for the vector store.', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Custom metadata for the vector store.', null=True)),
                ('status', models.CharField(choices=[('expired', 'expired'), ('in_progress', 'in_progress'), ('completed', 'completed')], default='in_progress', help_text='The current status of the vector store.', max_length=20)),
                ('usage_bytes', models.BigIntegerField(default=0, help_text='The total number of bytes used by the vector store.')),
                ('created_at', models.PositiveIntegerField(help_text='The Unix timestamp (in seconds) for when the vector store was created.')),
                ('last_active_at', models.PositiveIntegerField(blank=True, help_text='The Unix timestamp (in seconds) for when the vector store was last active.', null=True)),
                ('upstream_url', models.URLField(blank=True, help_text='The upstream API URL this vector store was created on', null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_stores', to='management.token')),
            ],
            options={
                'verbose_name': 'Vector Store',
                'verbose_name_plural': 'Vector Stores',
            },
        ),
        migrations.CreateModel(
            name='VectorStoreFileBatch',
            fields=[
                ('id', models.CharField(editable=False, help_text='The vector store file batch identifier.', max_length=100, primary_key=True, serialize=False)),
                ('file_counts', models.JSONField(default=dict, help_text='Processing counts (completed/failed/total/cancelled/in_progress).')),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='in_progress', help_text='The current status of the batch.', max_length=20)),
                ('created_at', models.PositiveIntegerField(help_text='The Unix timestamp (in seconds) for when the batch was created.')),
                ('vector_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_batches', to='management.vectorstore')),
            ],
            options={
                'verbose_name': 'Vector Store File Batch',
                'verbose_name_plural': 'Vector Store File Batches',
            },
        ),
        migrations.CreateModel(
            name='VectorStoreFile',
            fields=[
                ('id', models.CharField(editable=False, help_text='The vector store file identifier.', max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='in_progress', help_text='Processing status of the file in the vector store.', max_length=20)),
                ('last_error', models.JSONField(blank=True, help_text='Error details if processing failed.', null=True)),
                ('created_at', models.PositiveIntegerField(help_text='The Unix timestamp (in seconds) for when the file was added to the vector store.')),
                ('usage_bytes', models.BigIntegerField(default=0, help_text='Bytes used in vector store (may differ from original file after chunking).')),
                ('file_obj', models.ForeignKey(help_text='Reference to the actual file object.', on_delete=django.db.models.deletion.CASCADE, related_name='vector_store_files', to='management.fileobject')),
                ('vector_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='management.vectorstore')),
                ('batch', models.ForeignKey(blank=True, help_text='The batch that created this file, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='management.vectorstorefilebatch')),
            ],
            options={
                'verbose_name': 'Vector Store File',
                'verbose_name_plural': 'Vector Store Files',
            },
        ),
    ]
