# Generated by Django 5.2.7 on 2026-01-30 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_request_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='errors',
        ),
        migrations.AddField(
            model_name='batch',
            name='remote_id',
            field=models.CharField(blank=True, help_text='Batch ID from the upstream API', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='preview',
            field=models.TextField(blank=True, help_text='Preview of file content (first 10 lines for JSONL files)', null=True),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='remote_id',
            field=models.CharField(blank=True, help_text="File ID from the upstream API (e.g., 'file-abc123' from OpenAI)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='upstream_url',
            field=models.URLField(blank=True, help_text='The upstream API URL this file was uploaded to', null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='error_file',
            field=models.ForeignKey(blank=True, help_text='The error file for the batch (set when batch completes with errors).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_batches', to='management.fileobject'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='output_file',
            field=models.ForeignKey(blank=True, help_text='The output file for the batch (set when batch completes).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_batches', to='management.fileobject'),
        ),
        migrations.AddIndex(
            model_name='fileobject',
            index=models.Index(fields=['remote_id'], name='fileobject_remote_id_idx'),
        ),
    ]
