# Generated by Django 5.2.7 on 2026-02-16 11:24

import django.db.models.deletion
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_file_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorStore',
            fields=[
                ('id', models.CharField(default=management.models.generate_vector_store_id, editable=False, help_text='The vector store identifier.', max_length=100, primary_key=True, serialize=False)),
                ('remote_id', models.CharField(blank=True, help_text="Vector store ID from the upstream API (e.g., 'vs_abc123' from OpenAI)", max_length=100, null=True)),
                ('name', models.CharField(help_text='The name of the vector store.', max_length=255)),
                ('expires_after', models.JSONField(blank=True, help_text='Expiration policy for the vector store.', null=True)),
                ('chunking_strategy', models.JSONField(blank=True, help_text='Chunking configuration for the vector store.', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Custom metadata for the vector store.', null=True)),
                ('status', models.CharField(choices=[('expired', 'expired'), ('in_progress', 'in_progress'), ('completed', 'completed')], default='in_progress', help_text='The current status of the vector store.', max_length=20)),
                ('usage_bytes', models.BigIntegerField(default=0, help_text='The total number of bytes used by the vector store.')),
                ('created_at', models.PositiveIntegerField(help_text='The Unix timestamp (in seconds) for when the vector store was created.')),
                ('last_active_at', models.PositiveIntegerField(blank=True, help_text='The Unix timestamp (in seconds) for when the vector store was last active.', null=True)),
                ('upstream_url', models.URLField(blank=True, help_text='The upstream API URL this vector store was created on', null=True)),
            ],
            options={
                'verbose_name': 'Vector Store',
                'verbose_name_plural': 'Vector Stores',
            },
        ),
        migrations.CreateModel(
            name='VectorStoreFile',
            fields=[
                ('id', models.CharField(default=management.models.generate_vector_store_file_id, editable=False, help_text='The vector store file identifier.', max_length=100, primary_key=True, serialize=False)),
                ('remote_id', models.CharField(blank=True, help_text='VectorStoreFile ID from the upstream API', max_length=100, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='in_progress', help_text='Processing status of the file in the vector store.', max_length=20)),
                ('last_error', models.JSONField(blank=True, help_text='Error details if processing failed.', null=True)),
                ('created_at', models.PositiveIntegerField(help_text='The Unix timestamp (in seconds) for when the file was added to the vector store.')),
                ('usage_bytes', models.BigIntegerField(default=0, help_text='Bytes used in vector store (may differ from original file after chunking).')),
            ],
            options={
                'verbose_name': 'Vector Store File',
                'verbose_name_plural': 'Vector Store Files',
            },
        ),
        migrations.CreateModel(
            name='VectorStoreFileBatch',
            fields=[
                ('id', models.CharField(default=management.models.generate_vector_store_file_batch_id, editable=False, help_text='The vector store file batch identifier.', max_length=100, primary_key=True, serialize=False)),
                ('remote_id', models.CharField(blank=True, help_text='Batch ID from the upstream API', max_length=100, null=True)),
                ('file_counts', models.JSONField(default=dict, help_text='Processing counts (completed/failed/total/cancelled/in_progress).')),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='in_progress', help_text='The current status of the batch.', max_length=20)),
                ('created_at', models.PositiveIntegerField(help_text='The Unix timestamp (in seconds) for when the batch was created.')),
            ],
            options={
                'verbose_name': 'Vector Store File Batch',
                'verbose_name_plural': 'Vector Store File Batches',
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='token',
            field=models.ForeignKey(blank=True, help_text='The token (API key) that created this batch.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='management.token'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_id__isnull', False)), fields=('token', 'remote_id'), name='unique_batch_token_remote_id'),
        ),
        migrations.AddConstraint(
            model_name='fileobject',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_id__isnull', False)), fields=('token', 'remote_id'), name='unique_fileobject_token_remote_id'),
        ),
        migrations.AddField(
            model_name='vectorstore',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_stores', to='management.token'),
        ),
        migrations.AddField(
            model_name='vectorstorefile',
            name='file_obj',
            field=models.ForeignKey(help_text='Reference to the actual file object.', on_delete=django.db.models.deletion.CASCADE, related_name='vector_store_files', to='management.fileobject'),
        ),
        migrations.AddField(
            model_name='vectorstorefile',
            name='vector_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='management.vectorstore'),
        ),
        migrations.AddField(
            model_name='vectorstorefilebatch',
            name='vector_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_batches', to='management.vectorstore'),
        ),
        migrations.AddField(
            model_name='vectorstorefile',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='The batch that created this file, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='management.vectorstorefilebatch'),
        ),
        migrations.AddIndex(
            model_name='vectorstore',
            index=models.Index(fields=['remote_id'], name='vectorstore_remote_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='vectorstore',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_id__isnull', False)), fields=('token', 'remote_id'), name='unique_vectorstore_token_remote_id'),
        ),
        migrations.AddIndex(
            model_name='vectorstorefilebatch',
            index=models.Index(fields=['remote_id'], name='vs_file_batch_remote_idx'),
        ),
        migrations.AddConstraint(
            model_name='vectorstorefilebatch',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_id__isnull', False)), fields=('vector_store', 'remote_id'), name='unique_vs_file_batch_vector_store_remote_id'),
        ),
        migrations.AddIndex(
            model_name='vectorstorefile',
            index=models.Index(fields=['remote_id'], name='vectorstorefile_remote_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='vectorstorefile',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_id__isnull', False)), fields=('vector_store', 'remote_id'), name='unique_vector_store_remote_id'),
        ),
    ]
