# Generated by Django 5.2.7 on 2026-04-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_file_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='oauth_group_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The OAuth group that created this team (auto-managed, not user-editable)', max_length=255, verbose_name='OAuth group name'),
        ),
        migrations.AlterField(
            model_name='request',
            name='model',
            field=models.CharField(blank=True, default='', help_text='Model used in request', max_length=255),
        ),
    ]
