# Generated by Django 5.2.7 on 2026-07-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_team_oauth_group_name_alter_request_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='daily_limit_multiplier',
            field=models.PositiveIntegerField(blank=True, help_text='Daily limit = per-minute limit x this. Null = fallback (default 1440). Valid range 1-1440 (a day has 1440 minutes). Lower = stricter sustained cap.', null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='hourly_limit_multiplier',
            field=models.PositiveIntegerField(blank=True, help_text='Hourly limit = per-minute limit x this. Null = fallback (default 60). Valid range 1-60 (an hour has 60 minutes). Lower = stricter sustained cap.', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='daily_limit_multiplier',
            field=models.PositiveIntegerField(blank=True, help_text='Daily limit = per-minute limit x this. Null = fallback (default 1440). Valid range 1-1440 (a day has 1440 minutes). Lower = stricter sustained cap.', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='hourly_limit_multiplier',
            field=models.PositiveIntegerField(blank=True, help_text='Hourly limit = per-minute limit x this. Null = fallback (default 60). Valid range 1-60 (an hour has 60 minutes). Lower = stricter sustained cap.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_limit_multiplier',
            field=models.PositiveIntegerField(blank=True, help_text='Daily limit = per-minute limit x this. Null = fallback (default 1440). Valid range 1-1440 (a day has 1440 minutes). Lower = stricter sustained cap.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hourly_limit_multiplier',
            field=models.PositiveIntegerField(blank=True, help_text='Hourly limit = per-minute limit x this. Null = fallback (default 60). Valid range 1-60 (an hour has 60 minutes). Lower = stricter sustained cap.', null=True),
        ),
    ]
