# Generated by Django 5.2.7 on 2026-07-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0009_team_oauth_group_name_alter_request_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="total_response_time_ms",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total response time, including the processing time in Aqueduct as well as the API response time, in milliseconds",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="response_time_ms",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Time taken by the API to respond, in milliseconds",
                null=True,
            ),
        ),
    ]
