# Generated by Django 5.2.7 on 2026-08-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("management", "0010_request_processing_time_ms_and_more")]

    operations = [
        migrations.CreateModel(
            name="Snippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name identifying this snippet.", max_length=127
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("config", "config"), ("plugin", "plugin")],
                        default="config",
                        max_length=20,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this snippet is enabled. At most one 'config' snippet may be active at a time.",
                    ),
                ),
                ("code", models.TextField(help_text="Python source of the snippet class.")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last modification time."),
                ),
            ],
            options={
                "verbose_name": "Snippet",
                "verbose_name_plural": "Snippets",
                "ordering": ("name", "type"),
            },
        )
    ]
