# Generated by Django 5.2.7 on 2026-09-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("management", "0011_snippet")]

    operations = [
        migrations.AddField(
            model_name="snippet", name="order", field=models.PositiveSmallIntegerField(default=0)
        )
    ]
