# Generated by Django 5.2.7 on 2026-10-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("management", "0011_snippet")]

    operations = [
        migrations.AddField(
            model_name="request",
            name="cached_input_tokens",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Input tokens read from the provider's prompt cache. "
                "These are included in input_tokens.",
            ),
        ),
    ]
