# Generated by Django 5.2.7 on 2026-10-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_org_daily_limit_multiplier_and_more'),
        ('management', '0012_request_cached_input_tokens'),
    ]

    operations = [
    ]
