# Generated by Django 5.2.7 on 2026-10-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0013_merge_20261008_0711"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="reasoning_tokens",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Tokens used for reasoning. These are included in output_tokens.",
            ),
        ),
    ]
